export default function needListSerializer(flaskNeed, i) {
  return {
    needId: flaskNeed[i].id,
    title: flaskNeed[i].name,
    affiliateLinkUrl: flaskNeed[i].affiliateLinkUrl,
    bankTrackId: flaskNeed[i].bank_track_id,
    category: flaskNeed[i].category,
    childGeneratedCode: flaskNeed[i].childGeneratedCode,
    childSayName: flaskNeed[i].childSayName,
    childDeliveryDate: flaskNeed[i].child_delivery_date,
    childId: flaskNeed[i].child_id,
    confirmDate: flaskNeed[i].confirmDate,
    confirmUser: flaskNeed[i].confirmUser,
    cost: flaskNeed[i].cost,
    created: flaskNeed[i].created,
    createdById: flaskNeed[i].created_by_id,
    deletedAt: flaskNeed[i].deleted_at,
    description: flaskNeed[i].description,
    descriptionTranslations: flaskNeed[i].description_translations, // { en: '' , fa: ''}
    titleTranslations: flaskNeed[i].name_translations, // { en: '' , fa: ''}
    details: flaskNeed[i].details,
    doingDuration: flaskNeed[i].doing_duration,
    donated: flaskNeed[i].donated,
    doneAt: flaskNeed[i].doneAt,
    expectedDeliveryDate: flaskNeed[i].expected_delivery_date,
    information: flaskNeed[i].information,
    isConfirmed: flaskNeed[i].isConfirmed,
    isDeleted: flaskNeed[i].isDeleted,
    isDone: flaskNeed[i].isDone,
    isReported: flaskNeed[i].isReported,
    isUrgent: flaskNeed[i].isUrgent,
    ngoId: flaskNeed[i].ngoId,
    ngoAddress: flaskNeed[i].ngoAddress,
    ngoName: flaskNeed[i].ngoName,
    ngoDeliveryDate: flaskNeed[i].ngo_delivery_date,
    oncePurchased: flaskNeed[i].oncePurchased,
    paid: flaskNeed[i].paid,
    purchaseCost: flaskNeed[i].purchase_cost,
    purchaseDate: flaskNeed[i].purchase_date,
    receiptCount: flaskNeed[i].receipt_count,
    receipts: flaskNeed[i].receipts,
    status: flaskNeed[i].status,
    statusDescription: flaskNeed[i].status_description,
    statusUpdatedAt: flaskNeed[i].status_updated_at,
    type: flaskNeed[i].type,
    typeName: flaskNeed[i].type_name,
    unavailableFrom: flaskNeed[i].unavailable_from,
    unconfirmedAt: flaskNeed[i].unconfirmed_at,
    unpaidCost: flaskNeed[i].unpaid_cost,
    unpayable: flaskNeed[i].unpayable,
    unpayableFrom: flaskNeed[i].unpayable_from,
    updated: flaskNeed[i].updated,
    payments: flaskNeed[i].payments, // []
    imageUrl: flaskNeed[i].imageUrl,
    needRetailerImg: flaskNeed[i].img,
  };
}
