export const WALLET_NONCE_REQUEST = 'WALLET_NONCE_REQUEST';
export const WALLET_NONCE_SUCCESS = ' WALLET_NONCE_SUCCESS';
export const WALLET_NONCE_FAIL = ' WALLET_NONCE_FAIL';

export const WALLET_VERIFY_REQUEST = 'WALLET_VERIFY_REQUEST';
export const WALLET_VERIFY_SUCCESS = ' WALLET_VERIFY_SUCCESS';
export const WALLET_VERIFY_FAIL = ' WALLET_VERIFY_FAIL';
export const WALLET_VERIFY_RESET = 'WALLET_VERIFY_RESET';

export const GET_ANALYTICS_NGOS_REQUEST = 'GET_ANALYTICS_NGOS_REQUEST';
export const GET_ANALYTICS_NGOS_SUCCESS = ' GET_ANALYTICS_NGOS_SUCCESS';
export const GET_ANALYTICS_NGOS_FAIL = ' GET_ANALYTICS_NGOS_FAIL';

export const GET_ANALYTICS_ECOSYSTEM_REQUEST = 'GET_ANALYTICS_ECOSYSTEM_REQUEST';
export const GET_ANALYTICS_ECOSYSTEM_SUCCESS = ' GET_ANALYTICS_ECOSYSTEM_SUCCESS';
export const GET_ANALYTICS_ECOSYSTEM_FAIL = ' GET_ANALYTICS_ECOSYSTEM_FAIL';

export const GET_ANALYTICS_CHILDREN_REQUEST = 'GET_ANALYTICS_CHILDREN_REQUEST';
export const GET_ANALYTICS_CHILDREN_SUCCESS = ' GET_ANALYTICS_CHILDREN_SUCCESS';
export const GET_ANALYTICS_CHILDREN_FAIL = ' GET_ANALYTICS_CHILDREN_FAIL';

export const GET_ANALYTICS_CHILD_REQUEST = 'GET_ANALYTICS_CHILD_REQUEST';
export const GET_ANALYTICS_CHILD_SUCCESS = ' GET_ANALYTICS_CHILD_SUCCESS';
export const GET_ANALYTICS_CHILD_FAIL = ' GET_ANALYTICS_CHILD_FAIL';

export const GET_ANALYTICS_NEED_REQUEST = 'GET_ANALYTICS_NEED_REQUEST';
export const GET_ANALYTICS_NEED_SUCCESS = 'GET_ANALYTICS_NEED_SUCCESS';
export const GET_ANALYTICS_NEED_FAIL = 'GET_ANALYTICS_NEED_FAIL';
