export const LIST_CAMPAIGN_REQUEST = 'LIST_CAMPAIGN_REQUEST';
export const LIST_CAMPAIGN_SUCCESS = 'LIST_CAMPAIGN_SUCCESS';
export const LIST_CAMPAIGN_FAIL = 'LIST_CAMPAIGN_FAIL';
export const LIST_CAMPAIGN_RESET = 'LIST_CAMPAIGN_RESET';

export const CREATE_CAMPAIGN_REQUEST = 'CREATE_CAMPAIGN_REQUEST';
export const CREATE_CAMPAIGN_SUCCESS = 'CREATE_CAMPAIGN_SUCCESS';
export const CREATE_CAMPAIGN_FAIL = 'CREATE_CAMPAIGN_FAIL';
export const CREATE_CAMPAIGN_RESET = 'CREATE_CAMPAIGN_RESET';
