export const CHILD_LIST_REQUEST = 'CHILD_LIST_REQUEST';
export const CHILD_LIST_SUCCESS = 'CHILD_LIST_SUCCESS';
export const CHILD_LIST_FAIL = 'CHILD_LIST_FAIL';
export const CHILD_LIST_RESET = 'CHILD_LIST_RESET';
