export const COUNTRY_LIST_REQUEST = 'COUNTRY_LIST_REQUEST';
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS';
export const COUNTRY_LIST_FAIL = 'COUNTRY_LIST_FAIL';
export const COUNTRY_LIST_RESET = 'COUNTRY_LIST_RESET';

export const STATE_LIST_REQUEST = 'STATE_LIST_REQUEST';
export const STATE_LIST_SUCCESS = 'STATE_LIST_SUCCESS';
export const STATE_LIST_FAIL = 'STATE_LIST_FAIL';
export const STATE_LIST_RESET = 'STATE_LIST_RESET';

export const CITY_LIST_REQUEST = 'CITY_LIST_REQUEST';
export const CITY_LIST_SUCCESS = 'CITY_LIST_SUCCESS';
export const CITY_LIST_FAIL = 'CITY_LIST_FAIL';
export const CITY_LIST_RESET = 'CITY_LIST_RESET';

export const COUNTRY_BY_ID_REQUEST = 'COUNTRY_BY_ID_REQUEST';
export const COUNTRY_BY_ID_SUCCESS = 'COUNTRY_BY_ID_SUCCESS';
export const COUNTRY_BY_ID_FAIL = 'COUNTRY_BY_ID_FAIL';
export const COUNTRY_BY_ID_RESET = 'COUNTRY_BY_ID_RESET';

export const CITY_BY_ID_REQUEST = 'CITY_BY_ID_REQUEST';
export const CITY_BY_ID_SUCCESS = 'CITY_BY_ID_SUCCESS';
export const CITY_BY_ID_FAIL = 'CITY_BY_ID_FAIL';
export const CITY_BY_ID_RESET = 'CITY_BY_ID_RESET';

export const CITIES_BY_IDS_REQUEST = 'CITIES_BY_IDS_REQUEST';
export const CITIES_BY_IDS_SUCCESS = 'CITIES_BY_IDS_SUCCESS';
export const CITIES_BY_IDS_FAIL = 'CITIES_BY_IDS_FAIL';
export const CITIES_BY_IDS_RESET = 'CITIES_BY_IDS_RESET';
