export const GET_SERVER_CHILDREN_REQUEST = 'GET_SERVER_CHILDREN_REQUEST';
export const GET_SERVER_CHILDREN_SUCCESS = 'GET_SERVER_CHILDREN_SUCCESS';
export const GET_SERVER_CHILDREN_FAIL = 'GET_SERVER_CHILDREN_FAIL';

export const GET_SERVER_NEEDS_REQUEST = 'GET_SERVER_NEEDS_REQUEST';
export const GET_SERVER_NEEDS_SUCCESS = 'GET_SERVER_NEEDS_SUCCESS';
export const GET_SERVER_NEEDS_FAIL = 'GET_SERVER_NEEDS_FAIL';

export const UPDATE_FLASK_REQUEST = 'UPDATE_FLASK_REQUEST'; // fetch from flask
export const UPDATE_SERVER_REQUEST = 'UPDATE_SERVER_REQUEST'; // update nest
export const UPDATE_SERVER_SUCCESS = 'UPDATE_SERVER_SUCCESS';
export const UPDATE_SERVER_FAIL = 'UPDATE_SERVER_FAIL';

export const FAMILY_NETWORK_REQUEST = 'FAMILY_NETWORK_REQUEST';
export const FAMILY_NETWORK_SUCCESS = 'FAMILY_NETWORK_SUCCESS';
export const FAMILY_NETWORK_FAIL = 'FAMILY_NETWORK_FAIL';

export const SIGNATURE_REQUEST = 'SIGNATURE_REQUEST';
export const SIGNATURE_SUCCESS = 'SIGNATURE_SUCCESS';
export const SIGNATURE_FAIL = 'SIGNATURE_FAIL';

export const WALLET_CONNECT_REQUEST = 'WALLET_CONNECT_REQUEST';
export const WALLET_CONNECT_SUCCESS = 'WALLET_CONNECT_SUCCESS';
export const WALLET_CONNECT_FAIL = 'WALLET_CONNECT_FAIL';
