export const GET_ALL_MIDJOURNEY_IMAGES_REQUEST = 'GET_ALL_MIDJOURNEY_IMAGES_REQUEST';
export const GET_ALL_MIDJOURNEY_IMAGES_SUCCESS = 'GET_ALL_MIDJOURNEY_IMAGES_SUCCESS';
export const GET_ALL_MIDJOURNEY_IMAGES_FAIL = 'GET_ALL_MIDJOURNEY_IMAGES_FAIL';

export const ARCHIVE_MIDJOURNEY_IMAGES_REQUEST = 'ARCHIVE_MIDJOURNEY_IMAGES_REQUEST';
export const ARCHIVE_MIDJOURNEY_IMAGES_SUCCESS = 'ARCHIVE_MIDJOURNEY_IMAGES_SUCCESS';
export const ARCHIVE_MIDJOURNEY_IMAGES_FAIL = 'ARCHIVE_MIDJOURNEY_IMAGES_FAIL';

export const SELECT_MIDJOURNEY_IMAGE_REQUEST = 'SELECT_MIDJOURNEY_IMAGE_REQUEST';
export const SELECT_MIDJOURNEY_IMAGE_SUCCESS = 'SELECT_MIDJOURNEY_IMAGE_SUCCESS';
export const SELECT_MIDJOURNEY_IMAGE_FAIL = 'SELECT_MIDJOURNEY_IMAGE_FAIL';
