export const ALL_NEEDS_REQUEST = 'ALL_NEEDS_REQUEST';
export const ALL_NEEDS_SUCCESS = 'ALL_NEEDS_SUCCESS';
export const ALL_NEEDS_FAIL = 'ALL_NEEDS_FAIL';
export const ALL_NEEDS_RESET = 'ALL_NEEDS_RESET';

export const CHILD_EXAMPLE_NEEDS_REQUEST = 'CHILD_EXAMPLE_NEEDS_REQUEST';
export const CHILD_EXAMPLE_NEEDS_SUCCESS = 'CHILD_EXAMPLE_NEEDS_SUCCESS';
export const CHILD_EXAMPLE_NEEDS_FAIL = 'CHILD_EXAMPLE_NEEDS_FAIL';
export const CHILD_EXAMPLE_NEEDS_RESET = 'CHILD_EXAMPLE_NEEDS_RESET';

export const CHILD_NEEDS_REQUEST = 'CHILD_NEEDS_REQUEST';
export const CHILD_NEEDS_SUCCESS = 'CHILD_NEEDS_SUCCESS';
export const CHILD_NEEDS_FAIL = 'CHILD_NEEDS_FAIL';
export const CHILD_NEEDS_RESET = 'CHILD_NEEDS_RESET';

export const CHILD_ONE_NEED_REQUEST = 'CHILD_ONE_NEED_REQUEST';
export const CHILD_ONE_NEED_SUCCESS = 'CHILD_ONE_NEED_SUCCESS';
export const CHILD_ONE_NEED_FAIL = 'CHILD_ONE_NEED_FAIL';
export const CHILD_ONE_NEED_RESET = 'CHILD_ONE_NEED_RESET';

export const SW_NEED_LIST_REQUEST = 'SW_NEED_LIST_REQUEST';
export const SW_NEED_LIST_SUCCESS = 'SW_NEED_LIST_SUCCESS';
export const SW_NEED_LIST_FAIL = 'SW_NEED_LIST_FAIL';
export const SW_NEED_LIST_RESET = 'SW_NEED_LIST_RESET';

export const UPDATE_NEED_CONFIRM_REQUEST = 'UPDATE_NEED_CONFIRM_REQUEST';
export const UPDATE_NEED_CONFIRM_SUCCESS = 'UPDATE_NEED_CONFIRM_SUCCESS';
export const UPDATE_NEED_CONFIRM_FAIL = 'UPDATE_NEED_CONFIRM_FAIL';
export const UPDATE_NEED_CONFIRM_RESET = 'UPDATE_NEED_CONFIRM_RESET';

export const UPDATE_ONE_NEED_REQUEST = 'UPDATE_ONE_NEED_REQUEST';
export const UPDATE_ONE_NEED_SUCCESS = 'UPDATE_ONE_NEED_SUCCESS';
export const UPDATE_ONE_NEED_FAIL = 'UPDATE_ONE_NEED_FAIL';
export const UPDATE_ONE_NEED_RESET = 'UPDATE_ONE_NEED_RESET';

export const ADD_ONE_NEED_REQUEST = 'ADD_ONE_NEED_REQUEST';
export const ADD_ONE_NEED_SUCCESS = 'ADD_ONE_NEED_SUCCESS';
export const ADD_ONE_NEED_FAIL = 'ADD_ONE_NEED_FAIL';
export const ADD_ONE_NEED_RESET = 'ADD_ONE_NEED_RESET';

export const DELETE_NEED_REQUEST = 'DELETE_NEED_REQUEST';
export const DELETE_NEED_SUCCESS = 'DELETE_NEED_SUCCESS';
export const DELETE_NEED_FAIL = 'DELETE_NEED_FAIL';