export const NGO_BY_ID_REQUEST = 'NGO_BY_ID_REQUEST';
export const NGO_BY_ID_SUCCESS = 'NGO_BY_ID_SUCCESS';
export const NGO_BY_ID_FAIL = 'NGO_BY_ID_FAIL';
export const NGO_BY_ID_RESET = 'NGO_BY_ID_RESET';

export const NGO_LIST_REQUEST = 'NGO_LIST_REQUEST';
export const NGO_LIST_SUCCESS = 'NGO_LIST_SUCCESS';
export const NGO_LIST_FAIL = 'NGO_LIST_FAIL';
export const NGO_LIST_RESET = 'NGO_LIST_RESET';
