export const NGO_BY_ID_REQUEST = 'NGO_BY_ID_REQUEST';
export const NGO_BY_ID_SUCCESS = 'NGO_BY_ID_SUCCESS';
export const NGO_BY_ID_FAIL = 'NGO_BY_ID_FAIL';
export const NGO_BY_ID_RESET = 'NGO_BY_ID_RESET';

export const NGO_LIST_REQUEST = 'NGO_LIST_REQUEST';
export const NGO_LIST_SUCCESS = 'NGO_LIST_SUCCESS';
export const NGO_LIST_FAIL = 'NGO_LIST_FAIL';
export const NGO_LIST_RESET = 'NGO_LIST_RESET';

export const UPDATE_NGO_IS_ACTIVE_REQUEST = 'UPDATE_NGO_IS_ACTIVE_REQUEST';
export const UPDATE_NGO_IS_ACTIVE_SUCCESS = 'UPDATE_NGO_IS_ACTIVE_SUCCESS';
export const UPDATE_NGO_IS_ACTIVE_FAIL = 'UPDATE_NGO_IS_ACTIVE_FAIL';

export const UPDATE_NGO_REQUEST = 'UPDATE_NGO_REQUEST';
export const UPDATE_NGO_SUCCESS = 'UPDATE_NGO_SUCCESS';
export const UPDATE_NGO_FAIL = 'UPDATE_NGO_FAIL';

export const ADD_NGO_REQUEST = 'ADD_NGO_REQUEST';
export const ADD_NGO_SUCCESS = 'ADD_NGO_SUCCESS';
export const ADD_NGO_FAIL = 'ADD_NGO_FAIL';