export const SW_DETAILS_REQUEST = 'SW_DETAILS_REQUEST';
export const SW_DETAILS_SUCCESS = 'SW_DETAILS_SUCCESS';
export const SW_DETAILS_FAIL = 'SW_DETAILS_FAIL';
export const SW_DETAILS_RESET = 'SW_DETAILS_RESET';

export const SW_LIST_REQUEST = 'SW_LIST_REQUEST';
export const SW_LIST_SUCCESS = 'SW_LIST_SUCCESS';
export const SW_LIST_FAIL = 'SW_LIST_FAIL';
export const SW_LIST_RESET = 'SW_LIST_RESET';
